exports.OPCode = {
  DISPATCH: 0,
  HEARTBEAT: 1,
  ID: 2,
  STATUS_UPDATE: 3,
  VOICE_STATE_UPDATE: 4,
  VOICE_SERVER_PING: 5,
  RESUME: 6,
  RECCONECT: 7,
  REQUEST_GUILD_MEMEBERS: 8,
  INVALID_SESSION: 9,
  HELLO: 10,
  HEARTBEAT_ACK: 11
};
exports.dispatch = {
  READY: "READY",
  GUILD_CREATE: "GUILD_CREATE",
  PRESENCE_UPDATE: "PRESENCE_UPDATE",
  TYPING_START: "TYPING_START",
  MESSAGE_CREATE: "MESSAGE_CREATE",
};
